### ISSUE TITLE
Redundant code in graph_attention_network.py

### ISSUE THREAD

**Issue by Vincent-bin** [qcappart/hybrid-cp-rl-solver#2]
```python
for l, layer in enumerate(self.embedding_layer[:-1]):
            g = layer(g)
            g.ndata["n_feat"] = torch.relu(g.ndata["n_feat"])
            g.edata["e_feat"] = torch.relu(g.edata["e_feat"])

last_layer = self.embedding_layer[-1]
g = last_layer(g)
g.ndata["n_feat"] = torch.relu(g.ndata["n_feat"])
g.edata["e_feat"] = torch.relu(g.edata["e_feat"])
```
I found this in the file `src/architecture/graph_attention_network.py` and I am confused. I think the last_layer operation can be merged into the for-loop. I guess you used it for debugging and forgot to revert it back?

**Comment by qcappart** [comment]
Yes, you're right ! This piece of code can be merged. It was done initially because we used another activation function for the last layer. I corrected it.
