### ISSUE TITLE
Error when I run 'run_training_dqn_tsptw.sh'

### ISSUE THREAD

**Issue by jiang-yuan** [qcappart/hybrid-cp-rl-solver#4]
$ ./run_training_dqn_tsptw.sh
***********************************************************
[INFO] TRAINING ON RANDOM INSTANCES: TSPTW
[INFO] n_city: 20
[INFO] grid_size: 100
[INFO] max_tw_gap: 10
[INFO] max_tw_size: 100
[INFO] seed: 1
***********************************************************
[INFO] TRAINING PARAMETERS
[INFO] algorithm: DQN
[INFO] batch_size: 32
[INFO] learning_rate: 0.000100
[INFO] hidden_layer: 2
[INFO] latent_dim: 32
[INFO] softmax_beta: 10
[INFO] n_step: -1
***********************************************************
Using backend: pytorch
/data/yjiang/anaconda3/lib/python3.7/site-packages/dgl/base.py:45: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  return warnings.warn(message, category=category, stacklevel=1)
***********************************************************
[INFO] NUMBER OF FEATURES
[INFO] n_node_feat: 6
[INFO] n_edge_feat: 5
***********************************************************
Traceback (most recent call last):
  File "src/problem/tsptw/main_training_dqn_tsptw.py", line 67, in <module>
    trainer.run_training()
  File "/data/yjiang/hybrid-cp-rl-solver/src/problem/tsptw/../../../src/problem/tsptw/learning/trainer_dqn.py", line 85, in run_training
    self.initialize_memory()
  File "/data/yjiang/hybrid-cp-rl-solver/src/problem/tsptw/../../../src/problem/tsptw/learning/trainer_dqn.py", line 137, in initialize_memory
    self.run_episode(0, memory_initialization=True)
  File "/data/yjiang/hybrid-cp-rl-solver/src/problem/tsptw/../../../src/problem/tsptw/learning/trainer_dqn.py", line 175, in run_episode
    graph = env.make_nn_input(cur_state, self.args.mode)
  File "/data/yjiang/hybrid-cp-rl-solver/src/problem/tsptw/../../../src/problem/tsptw/environment/environment.py", line 72, in make_nn_input
    g.edata['e_feat'] = self.edge_feat_tensor
  File "/data/yjiang/anaconda3/lib/python3.7/site-packages/dgl/view.py", line 197, in __setitem__
    self._graph._set_e_repr(self._etid, self._edges, {key : val})
  File "/data/yjiang/anaconda3/lib/python3.7/site-packages/dgl/heterograph.py", line 3899, in _set_e_repr
    ' Got %d and %d instead.' % (nfeats, num_edges))
dgl._ffi.base.DGLError: Expect number of features to match number of edges. Got 380 and 0 instead.

I installed the version of DGL with CUDA 10.2.

**Comment by qcappart** [comment]
Hello ! I cannot reproduce your error on my computer. Could you try to install the CPU build of DGL ? Or another GPU build ?

`conda install -c dglteam dgl`

https://docs.dgl.ai/en/0.4.x/install/

If it is works, then I will know that the issue is related to the DGL/CUDA 10.2 build. Thanks !

**Comment by jiang-yuan** [comment]
> conda install -c dglteam dgl

I try to reinstall the dgl by conda install -c dglteam dgl, it installs dgl-0.5.2 instead of 0.4.x.
conda install -c dglteam dgl-cuda10.2  also installs dgl-0.5.2.

These both show the same error above.

But I do not know how to specify conda to install 0.4.x with cuda10.2

Could you try to upgrade dgl and try if it works in dgl-0.5.2?

**Comment by jiang-yuan** [comment]
> 
> 
> Hello ! I cannot reproduce your error on my computer. Could you try to install the CPU build of DGL ? Or another GPU build ?
> 
> `conda install -c dglteam dgl`
> 
> https://docs.dgl.ai/en/0.4.x/install/
> 
> If it is works, then I will know that the issue is related to the DGL/CUDA 10.2 build. Thanks !

Both `conda install -c dglteam dgl` and 'conda install -c dglteam dgl-cuda10.2' show same error above, they install dgl-0.5.2 instead of 0.4.x.
Could you try to upgrade dgl to 0.5.2 and check if it works?

**Comment by qcappart** [comment]
Indeed. It seems there are some incompatibilities with version 0.5.x of DGL. I cannot resolve it now. In the meantime, is it possible for you to use `dgl=0.4.2` proposed in the .yml file ?

**Comment by jiang-yuan** [comment]
> 
> 
> Indeed. It seems there are some incompatibilities with version 0.5.x of DGL. I cannot resolve it now. In the meantime, is it possible for you to use `dgl=0.4.2` proposed in the .yml file ?

According to the release document of DGL, only 0.5.x support cuda10.2.
I think I can try to create another conda env. Which version of CUDA you are using?

**Comment by qcappart** [comment]
It should work with this CUDA version:

`Cuda compilation tools, release 11.0, V11.0.221`

**Comment by jiang-yuan** [comment]
> 
> 
> It should work with this CUDA version:
> 
> `Cuda compilation tools, release 11.0, V11.0.221`

OK. I run it successfully by creat env by yml you provided.

**Comment by qcappart** [comment]
Great ! :-) Feel free to reach me again in case of questions.
