### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by jiang-yuan** [qcappart/hybrid-cp-rl-solver#5]
Last time I create env by the .yml you provide. It installs PyTorch 1.4.0.
I run the code successfully in CPU mode.
But when I change to mode to 'gpu',   I try CUDA 10.1 and 10.2 it shows same error:
    trainer = TrainerDQN(args)                                                        [80/879]
  File "/data/yjiang/hybrid-cp-rl-solver/src/problem/tsptw/../../../src/problem/tsptw/learning
/trainer_dqn.py", line 57, in __init__
    self.brain = BrainDQN(self.args, self.num_node_feats, self.num_edge_feats)
  File "/data/yjiang/hybrid-cp-rl-solver/src/problem/tsptw/../../../src/problem/tsptw/learning
/brain_dqn.py", line 39, in __init__
    self.model.cuda()
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/nn/modules
/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/nn/modules
/module.py", line 201, in _apply
    module._apply(fn)
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/nn/modules
/module.py", line 201, in _apply
    module._apply(fn)
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/nn/modules
/module.py", line 201, in _apply
    module._apply(fn)
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/nn/modules
/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/nn/modules
/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/cuda/__ini
t__.py", line 196, in _lazy_init
    _check_driver()
  File "/data/yjiang/anaconda3/envs/dp-solver-env/lib/python3.7/site-packages/torch/cuda/__ini
t__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by qcappart** [comment]
Hello,

I saw that you closed the issue. Was it resolved ? If so, could you tell me what was the problem ?

Many thanks !

Quentin

**Comment by jiang-yuan** [comment]
> 
> 
> Hello,
> 
> I saw that you closed the issue. Was it resolved ? If so, could you tell me what was the problem?
> 
> Many thanks !
> 
> Quentin

The Pytorch 1.4.0 installed by .yml is a cpu-based version. I uninstall it and reinstall it with cudatookit=10.1.
Then the numpy 1.18.0 shows some error so I update it to 1.19.2.
After these operations, I solve the problem.

But I have one more question here:
For 100 iterations, it takes 77 seconds even I use gpu mode dqn for tsptw with a 2080ti GPU and it has not finished training yet. In nvidia-smi, it only uses 11% gpu-memory.  In your paper, you wrote that you used a V100 GPU.
If I want to speed up the training, how should I adjust the parameters?


Plus, did you do experiments for tsptw with settransformer? If so, could you release this code?

**Comment by qcappart** [comment]
> The Pytorch 1.4.0 installed by .yml is a cpu-based version. I uninstall it and reinstall it with cudatookit=10.1.
> Then the numpy 1.18.0 shows some error so I update it to 1.19.2.
> After these operations, I solve the problem.

Great !

> For 100 iterations, it takes 77 seconds even I use gpu mode dqn for tsptw with a 2080ti GPU and it has not finished training yet. In nvidia-smi, it only uses 11% gpu-memory. In your paper, you wrote that you used a V100 GPU.
> If I want to speed up the training, how should I adjust the parameters?

It is 77 seconds for the 100 first iterations, or 77 seconds in average during the training ? At the beginning of DQN training, there is the initialization of the experience replay buffer to take into account.

In order to speed up the training, you can either reduce the _latent_dim_, and _hidden_layer_ values. You can directly change the embedding size of the GNN ([actor_critic.py](https://github.com/qcappart/hybrid-cp-rl-solver/blob/master/src/problem/tsptw/learning/actor_critic.py)).

```python 
self.embedding = [(num_node_feat, num_edge_feat), (self.args.latent_dim, self.args.latent_dim),(self.args.latent_dim, self.args.latent_dim), (self.args.latent_dim, self.args.latent_dim), (self.args.latent_dim, self.args.latent_dim)]
```

> Plus, did you do experiments for tsptw with settransformer? If so, could you release this code?

Concerning setTransformer, we only applied to Knapsack/Portfolio optimization, not for the TSPTW (because a GNN seemed more natural to use).

**Comment by jiang-yuan** [comment]
> > For 100 iterations, it takes 77 seconds even I use gpu mode dqn for tsptw with a 2080ti GPU and it has not finished training yet. In nvidia-smi, it only uses 11% gpu-memory. In your paper, you wrote that you used a V100 GPU.
> > If I want to speed up the training, how should I adjust the parameters?
> 
> It is 77 seconds for the 100 first iterations, or 77 seconds in average during the training ? At the beginning of DQN training, there is the initialization of the experience replay buffer to take into account.

E.g.
For 358500-358600, the time is 274393.43-275013.76

**Comment by jiang-yuan** [comment]
[DATA] 770300 608513.69 52.37523678213343 1.1398 10                                           │·······························
[DATA] 770400 608590.21 52.4848292663788 1.1854 10                                            │·······························
[DATA] 770500 608664.92 52.43037261040371 1.0558 10                                           │·······························
[DATA] 770600 608741.72 52.59559138179524 1.0855000000000001 10                               │·······························
[DATA] 770700 608818.64 52.48324461500005 1.1956 10                                           │·······························
[DATA] 770800 608896.21 52.42943812663398 1.0277999999999998 10                               │·······························
[DATA] 770900 608972.84 52.37360805801647 1.0473 10                                           │·······························
[DATA] 771000 609048.91 52.261011572108515 1.0644999999999998 10                              │·······························
[DATA] 771100 609123.44 52.26197758402259 1.0706999999999998 10                               │·······························
[DATA] 771200 609199.93 52.346989059485686 1.0372 10                                          │·······························
[DATA] 771300 609276.46 52.23356561514626 0.9480999999999999 10                               │·······························
[DATA] 771400 609353.29 52.346246091294724 0.8809 10                                          │·······························
[DATA] 771500 609430.66 52.46014286093837 0.9368 10                                           │·······························
[DATA] 771600 609506.01 52.43067999760513 0.9825999999999997 10                               │·······························
[DATA] 771700 609582.99 52.09947177830667 1.0234 10                                           │·······························
[DATA] 771800 609660.5 52.486946816216886 1.0957999999999997 10                               │·······························
[DATA] 771900 609737.83 52.40225741046224 1.0303 10                                           │·······························
[DATA] 772000 609815.0 52.62362475281887 1.0438 10                                            │·······························
[DATA] 772100 609890.4 52.67899098989057 0.8506 10                                            │·······························
[DATA] 772200 609967.79 52.59674043021218 0.9287999999999997 10                               │·······························
[DATA] 772300 610045.35 52.62239570810179 0.8998 10                                           │·······························
[DATA] 772400 610122.7 52.54331529568568 0.7719999999999999 10                                │·······························
[DATA] 772500 610200.16 52.540514088253815 0.8964000000000001 10                              │·······························
[DATA] 772600 610275.48 52.56762984985745 0.9435999999999999 10                               │·······························
[DATA] 772700 610353.07 52.596271563066814 0.9634 10                                          │·······························
[DATA] 772800 610430.36 52.53770341526969 0.8975 10                                           │·······························
[DATA] 772900 610508.38 52.56574202136456 0.8998 10                                           │·······························
[DATA] 773000 610584.18 52.512156448857326 0.8968 10                                          │·······························
[DATA] 773100 610661.98 52.622057489820776 0.9421999999999999 10                              │·······························
[DATA] 773200 610739.3 52.401076813296726 0.8983000000000001 10                               │·······························
[DATA] 773300 610816.64 52.457045924412625 0.9115000000000001 10                              │·······························
[DATA] 773400 610894.21 52.64951340763671 0.9349999999999999 10                               │·······························
[DATA] 773500 610971.36 52.62255136883846 0.8717 10                                           │·······························
[DATA] 773600 611046.34 52.42864101581336 0.9026 10                                           │·······························
[DATA] 773700 611123.48 52.51066701240413 0.8743000000000001 10                               │·······························
[DATA] 773800 611202.04 52.5385930807676 0.9102 10

**Comment by qcappart** [comment]
Execution time seems to be similar to what we obtained.

e.g., (in [tsptw20-dqn](https://github.com/qcappart/hybrid-cp-rl-solver/blob/master/selected-models/dqn/tsptw/n-city-20/grid-100-tw-10-100/log-training.txt))

> [DATA] 358500 356347.23 4.513736769079761 0.021599999999999998 10
> [DATA] 358600 356446.25 4.480153059124009 0.0207 10
